require('./All.test')
require('./Any.test')
require('./First.test')
require('./Last.test')
require('./List.test')
require('./List.test')
require('./Max.test')
require('./Min.test')
require('./Product.test')
require('./Sum.test')
require('./Tuple.test')
require('./Tuple4.test')

require('./E2E')
